server:
  port: 8764


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-ribbon

#Feign是自带断路器的，在D版本的Spring Cloud之后它没有默认打开。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true